<?php
use Drupal\commerce_order\Entity\Order;

function tintorero_preprocess_commerce_cart_block(&$variables) {
  $query = \Drupal::entityQuery('commerce_order')
    ->condition('uid',\Drupal::currentUser()->id())
    // ...which are carts
    ->condition('cart', 1)
    // ...last created last
    ->sort('created', 'ASC')
    // ...get only one
    ->range(0,1);

  // execute this : you get an array of a unique order ids (last cart)
  $cartsOrders = $query->execute();
  // I found one : this user has a cart
  if(count($cartsOrders) > 0) {
    $variables['cartid'] = key($cartsOrders);
  }
}
